### ISSUE TITLE
Editable Objects implement serialization

### ISSUE THREAD

**Issue by snotbane** [Brungleby/Mithril.Core#4]
EditableObjects should be able to be loaded, saved, and edited such that the serialized form supports arrays with subclasses. This can be done in one of two ways:

- Use a custom serialization protocol that explicitly defines the types of each object
- Pass a custom array object into the built-in serialization protocol that explicitly defines the type of each object that is stored inside. (Or create an attribute that does this automatically.) This option is the better of the two but it may or may not actually work.

**Comment by snotbane** [comment]
The initial issue with the custom array is that because its contents are all stored as the base class, any custom data is lost. In order for this to work, we'll need to effectively create a new object with its own fields for each specific object in the array. This way, all subclasses' data will be stored correctly.

**Comment by snotbane** [comment]
Something else to keep in mind is a situation like this:
```
class Animal : object;
class Dog : Animal;

class Container : object
{ public Animal contents; }

static class Main
{
    static void Main()
    {
        var container = new Container() { contents = new Dog() };
    }
}
```
In this example, any data kept in `Dog` may be lost because it is being stored as an `Animal`.

For this reason, it's possible that ANY object value must have its type specified in serialization. An attribute (e.g. `[SerializeType]`) that accomplishes this would be ideal.

**Comment by Sam-Gideone** [comment]
I think it's important to note that C# has been expressly designed to ensure that Type Erasure (which is dataloss when a type is changed) isn't _**ever**_ possible. This is because in C# it is not possible to change the type of an object, and therefore erasure can never occur. Even when an object is casted to its basetype it still has all of its data — including its final concrete type.

Lets use that same animal example:
```csharp
public abstract class Animal : Object;
public class Dog : Animal;
public class Cat : Animal;

static class Main
{
    static void Main()
    {
        var list = new List<Animal>() { new Dog(), new Cat() };
        Debug.Log(list[0].GetType().Name); // Prints: "Dog"
        Debug.Log(list[1].GetType().Name); // Prints: "Cat"
    }
}
```

This same principle applies to all types, not just classes.
Here is another example that uses an object list:
```csharp
static class Main
{
    static void Main()
    {
        var list = new List<object>() { "Niiiice.",  5,  3f };
        Debug.Log(list[0].GetType().Name); // Prints: "String"
        Debug.Log(list[1].GetType().Name); // Prints: "Int"
        Debug.Log(list[2].GetType().Name); // Prints: "Single"
    }
}
```
This is important, because if the type survives _so does all its data along with it_.
For example, we can use reflection to get this data:
```csharp
static class Main
{
    static void Main()
    {
        var list = new List<object>() { "Niiiice." };

        object instance = list[0];

        var fields = instance.GetType().GetFields(BindingFlags.Private | BindingFlags.Public | BindingFlags.Instance);
        // It should be noted that the inputted BindingFlags is important.
        // Also... inherited private fields will not be found! For that you need to use recursion.
        
        object valueOfFirstField = fields[0].GetValue(instance);
    }
}
```
Point is — it should be possible to write an entirely automatic and generic serialization system that can convert anything into a JSON format with only the information contained in the object itself. However, writing this system is still a fair bit of work and rather complex. Plus, determining what data is 'essential' or 'inessential' would need to be added (likely through the use of attributes on the fields themselves).

**Comment by snotbane** [comment]
Closing this issue. Serialization is at a stable point. `EditableObject`s will be deprecated and replaced with `SmartObject`s.
